// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  ACCOUNT_ID: string;
  GATEWAY_ID: string;
  GatewayToken: any;

  AZURE_RESOURCE?: string;
  AZURE_API_VERSION?: string;
}

type Logger = {
  info: (message: string, data?: Record<string, any>) => void;
  error: (message: string, error?: Error | Record<string, any>) => void;
  warn: (message: string, data?: Record<string, any>) => void;
};
